sudo: required

services:
- docker
before_install:
  - docker pull lineageos4microg/docker-lineage-cicd:latest
  - travis_wait 200 docker run -e "BRANCH_NAME=lineage-16.0" -e "DEVICE_LIST=bacon" -e "SIGN_BUILDS=true" -e "SIGNATURE_SPOOFING=restricted" -e "INCLUDE_PROPRIETARY=true" -v "/home/user/lineage:/srv/src" -v "/home/user/zips:/srv/zips" -v "/home/user/logs:/srv/logs" -v "/home/user/cache:/srv/ccache" -v "/home/user/keys:/srv/keys" -v "/home/user/manifests:/srv/local_manifests" lineageos4microg/docker-lineage-cicd
script:
  - docker ps | grep -q
