sudo: required

cache:
  directories:
  - $HOME/lineage
  - $HOME/zips
  - $HOME/logs
  - $HOME/cache
  - $HOME/keys
  - $HOME/manifests
services:
- docker
before_install:
  - docker pull lineageos4microg/docker-lineage-cicd:latest
  - travis_wait 720 sleep infinity & docker run -e "BRANCH_NAME=lineage-16.0" -e "DEVICE_LIST=bacon" -e "SIGN_BUILDS=true" -e "SIGNATURE_SPOOFING=restricted" -e "INCLUDE_PROPRIETARY=true" -v "$HOME/lineage:/srv/src" -v "$HOME/zips:/srv/zips" -v "$HOME/logs:/srv/logs" -v "$HOME/cache:/srv/ccache" -v "$HOME/keys:/srv/keys" -v "$HOME/manifests:/srv/local_manifests" lineageos4microg/docker-lineage-cicd
script:
  - docker ps | grep -q
